INSERT INTO `equipes` (`id`, `nom`, `pays`, `rang`) VALUES
(1, 'Die Mannschaft', 'Allemagne', 1),
(2, 'Auriverdes', 'Bresil', 2),
(3, 'Las Quinas', 'Portugal', 3),
(4, 'La Albiceleste', 'Argentine', 4),
(5, 'Les diables rouges', 'Belgique', 5),
(6, 'la roja', 'Espagne', 6),
(7, 'Biale Orly', 'Pologne', 7),
(8, 'La Nati', 'Suisse', 8),
(9, 'Les tricolores', 'France', 9),
(10, 'Viva vodka', 'Russie', 10),
(11, 'La Selecion Inca', 'Perou', 11),
(12, 'Danish Dynamite', 'Danemark', 12),
(13, 'Plata o plomo', 'Colombie', 13),
(14, 'The Three Lions', 'Angleterre', 14),
(15, 'El Tri', 'Mexique', 15),
(16, 'Kockasti', 'Croatie', 16),
(17, 'Blagult', 'Suede', 17),
(18, 'La celeste', 'Uruguay', 18),
(19, 'Strakarnir okkar', 'Islande', 19),
(20, 'Les Lions de la Teranga', 'Senegal', 20),
(21, 'Los Ticos', 'Costa_Rica', 21),
(22, 'Les aigles de Carthage', 'Tunisie', 22),
(23, 'Les pharaons', 'Egypte', 23),
(24, 'Les lions de Perse', 'Iran', 24),
(25, 'Beli Orlovi', 'Serbie', 25),
(26, 'Socceroos', 'Australie', 26),
(27, 'Les lions de l\'atlas', 'Maroc', 27),
(28, 'Super eagles', 'Nigeria', 28),
(29, 'Les samourais bleus', 'Japon', 29),
(30, 'Los canaleros', 'Panama', 30),
(31, 'Les Guerriers Taegeuk', 'Coree_du_sud', 31),
(32, 'Les fils du désert', 'Arabie_Saoudite', 32);